service: pokefinder

provider:
  name: aws
  runtime: nodejs 16.x
  profile: serverlessUser
  region:  eu-west-1

plugins:
   - serverless-s3-sync

custom:
  bucketName: my-serverless-react-app-4556
  s3Sync:
      - bucketName: ${self:custom.bucketName}
        localDir: pokefinder/build/

resources:
  Resources:
      ReactAppBucket:
        Type: AWS::S3::BUcket
        Properties:
           BucketName: ${self:custom.bucketName}
           AccessControl: PublicRead
           WevsiteConfiguration:
              IndexDocument: index.html
              ErrorDocument: index.html
      S3AccessPolicy:
          Type: AWS::S3::BucketPolicy
          Properties:
              Bucket:
                Ref: ReactAppBucket
              PolicyDocument:
                Statement:
                - Sid: PublicReadGetObject
                  Effect: Allow
                  Principal: '*'
                  Action:
                    -s3:GetObject
                  Resource: arn:aws:s3:s3:::${self:custom.bucketName}/*
      CloudFromDistribution:
          Type: AWS::CloudFront::Distribution
          Properties:
            DistributionConfig:
                Origins:
                    - DomainName: ${custom:self.bucketName}.s3.amazonaws.com
                      ID: ReactApp
                      CustomOriginConfig:
                          HTTPPort: 80
                          HTTPSPort: 443
                          OriginProtocolPolicy: https-only
                Enabled: 'true'
                DefaultRootObject: index.html
                CustomErrorResponses:
                     - ErrorCode: 404
                       Response: 200
                       ResponsePagePath: /index.html
                DefaultCacheBehavior:
                      AllowedMethods:
                        - DELETE
                        - GET
                        - HEAD
                        - OPTIONS
                        - PATCH
                        - POST
                        - PUT
                      TargetOriginId: ReactApp
                      ForwardedValues:
                         QueryString : 'false'
                         Cookies:
                            Forward: none
                      ViewerProtocolPolicy: redirect-to-https
                ViewerCertificate:
                      CloudFrontDefaultCertificate: true
                      

         